apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot_health
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kwbach/springboot_health_config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
