apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: demo
  name: demo
  namespace: web
spec:
  clusterIP: 10.100.169.90
  clusterIPs:
  - 10.100.169.90
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  sessionAffinity: None
  type: ClusterIP
