apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-health
  name: spring-health
  namespace: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-health
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-health
    spec:
      containers:
        - image: docker.io/kbachman/kubernetes:f891336
          name: kubernetes
          resources: {}
      imagePullSecrets:
        - name: regsecret
status: {}
